language: r
cran: http://cran.rstudio.com

sudo: false

cache:
  packages: yes
  directories:
    - $TRAVIS_BUILD_DIR/_bookdown_files
env:
  global:
    - GIT_AUTHOR_NAME: "Altaf Ali"
    - GIT_AUTHOR_EMAIL: "altaf@fastmail.com"
    - secure: "e5GMjvwyOSv1Da9RKSryXsef/zezrpglPws1QjC/VWv2SUpkCyObQF09JQz27FVtKS4SC2gunTipaeRyLyrZ4oEAwb6igPhYmG3tZZHljpBpbW4OxqvmFQf/b4t6NC65h9END3XY4Yic0cWfuM2qksLUMtgUtWBxLLhI3vJiIIfBKHjwuGj/c0YhtQwRxi3W2nztOIgVlQeB7gaqgoOfHYK+iQmoy0K9VKrenIiaefkb65CfPEQRqgAXAXvJnpz8zJc3V0dmm7donQyI2ykx+VPFS+FBMDEg1RzvN3VQPqa3aiQLipWurboz9Ki9CkitPN46Dk8VQ3OH2GsHnlxxTtBK5/CoEh81hmRgrxtRWeB4uMbCDZaQKkgrjwaGJ47rXYxKfk02hDRdIypM/fpHA5ahj/DFawI/jUpBmYaMEUSb1XKoZ8mvmfjyAUAnOduf5CXveRHnx06TGQsDTWhIU+fRcrFvOoZQtFuzYUgY70B0RUYzOl2EuCs6S41q84HajvuivEMN4XSrWBR18jzRlyqUv4pEhFrNVQW+k9Q/H9ad7yoeO+nTDlnUAk8zV37FM/WxU1fNHsxF+bfghBCjtT8d/GXEOqSoOcNaxKEU3RLZJoVu9yh6nom1qgYAdareZD/7TgzmYzj0VKjCRMzVkhL1NHskdPd+7KuploLE5ys="

before_script:
  - chmod +x ./bin/_build.sh
  - chmod +x ./bin/_deploy.sh

script:
  - ./bin/_build.sh
  - ./bin/_deploy.sh

